version: 0.2

env:
  variables:
    CHILD_TEMPLATES: |
      sema4-vpc.yaml
      aws-genomics-s3.template.yaml
      aws-genomics-iam.template.yaml
      aws-custom-ami.template.yaml
      aws-genomics-batch.template.yaml
      aws-cromwell-server.template.yaml
      sema4-serverless-rdb.yaml
    TEMPLATE_FILES: |
      sema4-valinor.yaml
      sema4-vpc.yaml
      aws-genomics-s3.template.yaml
      aws-genomics-iam.template.yaml
      aws-custom-ami.template.yaml
      aws-genomics-batch.template.yaml
      aws-cromwell-server.template.yaml
      sema4-serverless-rdb.yaml
    CONFIG_FILES: |
      config-test.json

phases:
  install:
    commands:
      npm install jsonlint -g
  pre_build:
    commands:
      - echo "Validating Valinor templates"
      - |
        for template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $template"
          aws cloudformation validate-template --template-body file://$template
        done
      - |
        for conf in $CONFIG_FILES; do
          echo "Validating CF parameters config file $conf"
          jsonlint -q $conf
        done
  build:
    commands:
      - echo "Copying child stack templates to S3"
      - |
        for child_template in $CHILD_TEMPLATES; do
          if [ "X$TEMPLATE_PREFIX" = "X" ]; then
            aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$child_template" --sse aws:kms
          else
            aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$TEMPLATE_PREFIX/$child_template" --sse aws:kms
          fi
        done
      - echo "Updating template configuration files to use the appropriate values"
      - |
        for conf in $CONFIG_FILES; do
          if [ "X$TEMPLATE_PREFIX" = "X" ]; then
            echo "Replacing \"TEMPLATE_PATH_PLACEHOLDER\" for \"$TEMPLATE_BUCKET\" in $conf"
            sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET/" $conf
            sed -i -e "s/DB_HOST_PLACEHOLDER/$DB_HOST_PARAM/" $conf
            sed -i -e "s/CROMWELL_SERVER_URL_PLACEHOLDER/$CROMWELL_SERVER_URL_PARAM/" $conf
          else
            echo "Replacing \"TEMPLATE_PATH_PLACEHOLDER\" for \"$TEMPLATE_BUCKET/$TEMPLATE_PREFIX\" in $conf"
            sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/$TEMPLATE_PREFIX/" $conf
            sed -i -e "s/DB_HOST_PLACEHOLDER/$DB_HOST_PARAM/" $conf
            sed -i -e "s/CROMWELL_SERVER_URL_PLACEHOLDER/$CROMWELL_SERVER_URL_PARAM/" $conf
          fi
        done

artifacts:
  files:
    - sema4-valinor.yaml
    - config-test.json
