AWSTemplateFormatVersion: '2010-09-09'
Description: Create Valinor Scalable genomics workflows environment
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Template path where those nested cloudformation templates are."
        Parameters:
          - TemplatePath

      - Label:
         default: Network Global CIDR and Subnet Network - Ask IT Support for Unique Global CIDR for Routing Among VPC or Organizational Sub Account
        Parameters:
          - AvailabilityZone1
          - AvailabilityZone2
          - GlobalCIDR
          - PubNet1
          - PubNet2
          - PrivNet1
          - PrivNet2

      - Label:
          default: "Genomics Environment for AWS Batch Parameters"
        Parameters:
          - S3BucketName
          - KeyPairName
          - ScratchVolumeSize
          - SpotBidPercentage
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - HighPriorityCEMinvCpus
          - HighPriorityCEMaxvCpus
          - DefaultRetryNumber
      - Label:
          default: "Cromwell Server Parameters"
        Parameters:
          - ServerInstanceType
          - ServerInstanceName
          - ServerSSHLocation
      - Label:
          default: "Serverless RDS Parameters"
          Parameters:
            - DBClusterIdentifier
            - DatabaseUsername
            - DatabasePassword

    ParameterLabels:
      TemplatePath:
        default: S3 key object (direcotry) name where templates locate.
      S3BucketName:
        default: S3 Bucket Name
      KeyPairName:
        default: EC2 Key Pair Name
      ScratchVolumeSize:
        default: Cromewll AMI Scratch Volume (GB)
      SpotBidPercentage:
        default: Spot Bid %
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU
      HighPriorityCEMinvCpus:
        default: High Priority Min vCPU
      HighPriorityCEMaxvCpus:
        default: High Priority Max vCPU
      DefaultRetryNumber:
        default: Job Retry Attempts
      ServerInstanceType:
        default: Cromwell Server Instance Type
      ServerInstanceName:
        default: Cromwell Server Instance Name
      ServerSSHLocation:
        default: Cromwell Server SSH Location

      DBClusterIdentifier:
        default: DB Cluster ID
      DatabaseUsername:
        default: Database Username
      DatabasePassword:
        default: Database Password

Parameters:
  TemplatePath:
    Type: String
    Description: S3Bucket Path where the templates are stored
    Default: s4-valinor-cloudformation-templates
  S3BucketName:
    Description: A S3 bucket name for storing analysis results
    Type: String
  AvailabilityZone1:
    Description: The first availability zone in the region
    Type: AWS::EC2::AvailabilityZone::Name
    ConstraintDescription: Must be a valid availability zone
    Default: us-east-1c
  AvailabilityZone2:
    Description: The second availability zone in the region
    Type: AWS::EC2::AvailabilityZone::Name
    ConstraintDescription: Must be a valid availability zone
    Default: us-east-1b
  GlobalCIDR:
    Description: Global CIDR of the VPC  ( i.e. 10.80.191.0/24 - Total 256 IPs )
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.0/24
  PubNet1:
    Description: 1st Public Subnet Network (i.e. 10.80.191.0/26 - Total 64 IPs )
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.0/26
  PubNet2:
    Description: 2nd Public Subnet Network (i.e. 10.80.191.64/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.64/26
  PrivNet1:
    Description: 1nd Private Subnet Network (i.e. 10.80.191.128/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.128/26
  PrivNet2:
    Description: 2nd Private Subnet Network (i.e. 10.80.191.192/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.192/26

  ScratchVolumeSize:
    Type: Number
    Default: 200
    Description: The initial size of the scratch volume for AMI
  KeyPairName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
  SpotBidPercentage:
    Description: The percent of on-demand pricing for max bid for Spot intances
    Type: Number
    Default: 100
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 1024
  HighPriorityCEMinvCpus:
    Description: The minimum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 0
  HighPriorityCEMaxvCpus:
    Description: The maximum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 1024
  DefaultRetryNumber:
    Description: The default number of Job retry attempts
    Type: Number
    Default: 3
  ServerInstanceType:
    Description: >-
      EC2 instance type.  Cromwell itself does not require much compute power.
      A t2.medium should be sufficient.  If you want to run this server on the
      free tier, use a t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - r5a.2xlarge
      - r5a.4xlarge
    ConstraintDescription: "Must be 't2.micro', 't2.medium', or 't2.large', or 't2.xlarge', or 't2.2xlarge'."
  ServerInstanceName:
    Type: String
    Default: cromwell-server
    Description: The name of the instance that is created
  ServerSSHLocation:
    Description: " The IP address range that can be used to SSH to the EC2 instances"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  HTTPLocation:
    Description: "The IP address range that has HTTP access to the EC2 instances"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  DBClusterIdentifier:
    Type: String
    Description: The DB cluster identifier. This parameter is stored as a lowercase string

  DatabaseUsername:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 1 to 16 alphanumeric characters.
    Description: The database admin account user name, between 1 to 16 alphanumeric characters.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 8 to 41 alphanumeric characters.
    Description: The database admin account password, between 8 to 41 alphanumeric characters.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/sema4-vpc.yaml"
      TimeoutInMinutes: 20
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"
      Parameters:
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        GlobalCIDR: !Ref GlobalCIDR
        PubNet1:  !Ref PubNet1
        PubNet2: !Ref PubNet2
        PrivNet1: !Ref PrivNet1
        PrivNet2: !Ref PrivNet2
  AMIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-custom-ami.template.yaml"
      TimeoutInMinutes: 20
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AMI"
      Parameters:
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        PublicSubnetID: !Sub ${VPCStack.Outputs.PublicSubnet2}
        ScratchMountPoint: /cromwell_root
        ScratchVolumeSize: !Ref ScratchVolumeSize
        UseEncryption: "Yes"
        KeyName: !Ref KeyPairName
        AMIType: cromwell
        AMIName: !Join ["-", ["cromwell-genomics-ami", !Select [2, !Split ["/", !Ref "AWS::StackId" ]]]]
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-s3.template.yaml"
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-S3Stack"
      Parameters:
        S3BucketName: !Ref S3BucketName
  IamStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-iam.template.yaml"
      TimeoutInMinutes: 20
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IAM"
      Parameters:
        S3BucketName: !Ref S3BucketName
  BatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamStack
      - VPCStack
      - AMIStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-batch.template.yaml"
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Batch"
      Parameters:
        CustomAmiId: !Sub ${AMIStack.Outputs.AMI}
        Ec2KeyPairName: !Ref KeyPairName
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        SubnetIds: !Sub "${VPCStack.Outputs.PrivateSubnet1},${VPCStack.Outputs.PrivateSubnet2}"
        SpotBidPercentage: !Ref SpotBidPercentage
        DefaultCEMinvCpus: !Ref DefaultCEMinvCpus
        DefaultCEMaxvCpus: !Ref DefaultCEMaxvCpus
        HighPriorityCEMinvCpus: !Ref HighPriorityCEMinvCpus
        HighPriorityCEMaxvCpus: !Ref HighPriorityCEMaxvCpus
        DefaultRetryNumber: !Ref DefaultRetryNumber
        BatchServiceRoleArn: !Sub ${IamStack.Outputs.BatchServiceRoleArn}
        Ec2InstanceProfileArn: !Sub ${IamStack.Outputs.BatchInstanceProfileArn}
        SpotFleetRoleArn: !Sub ${IamStack.Outputs.BatchSpotFleetRoleArn}
  CromwellServerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BatchStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-cromwell-server.template.yaml"
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-CromwellServer"
      Parameters:
        InstanceType: !Ref ServerInstanceType
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        PublicSubnetID: !Sub ${VPCStack.Outputs.PublicSubnet2}
        LatestAmazonLinuxAMI: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2
        InstanceName: !Ref ServerInstanceName
        KeyName: !Ref KeyPairName
        SSHLocation: !Ref ServerSSHLocation
        HTTPLocation: !Ref HTTPLocation
        S3BucketName: !Ref S3BucketName
        BatchQueue: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to RDS
      VpcId: !Sub ${VPCStack.Outputs.VPCId}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Sub "${CromwellServerStack.Outputs.EC2SecurityGroup}"
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Sub "${BatchStack.Outputs.GenomicsBatchSecurityGroup}"
  ServerlessRDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CromwellServerStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/sema4-serverless-rdb.yaml"
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ServerlessRDS"
      Parameters:
        DBClusterIdentifier: !Ref DBClusterIdentifier
        DatabaseName: cromwell
        DatabaseUsername: !Ref DatabaseUsername
        DatabasePassword: !Ref DatabasePassword
        VpcSecurityGroupIds: !Ref RDSSecurityGroup
        DatabaseSubnets: !Sub "${VPCStack.Outputs.PublicSubnet1},  ${VPCStack.Outputs.PublicSubnet2}"

Outputs:
  GenomicsEnvS3Bucket:
    Value: !Sub ${S3Stack.Outputs.BucketName}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-S3Bucket"
  GenomicsEnvBatchJobRoleArn:
    Value: !Sub ${IamStack.Outputs.BatchJobRoleArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-BatchJobRoleArn"
  GenomicsEnvDefaultJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-DefaultJobQueueArn"
  GenomicsEnvHighPriorityJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.HighPriorityJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-HighPriorityJobQueueArn"

  ServerEC2Instance:
    Description: The EC2 Instance ID of your Cromwell Server
    Value: !Sub ${CromwellServerStack.Outputs.EC2Instance}

  ServerPublicIp:
    Value: !Sub ${CromwellServerStack.Outputs.PublicIp}
    Description: Cromwell server public IP address

  ServerHostName:
    Value: !Sub ${CromwellServerStack.Outputs.HostName}
    Description: Cromwell server public DNS name

