AWSTemplateFormatVersion: '2010-09-09'
Description: Create Scalable workflows bastion environment
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Template path where those nested cloudformation templates are."
        Parameters:
          - TemplatePath

      - Label:
         default: Network Global CIDR and Subnet Network - Ask IT Support for Unique Global CIDR for Routing Among VPC or Organizational Sub Account
        Parameters:
          - GlobalCIDR
          - PubNet1
          - PubNet2
          - PrivNet1
          - PrivNet2
          - AvailabilityZone1
          - AvailabilityZone2

      - Label:
          default: "Genomics Environment for AWS Batch Parameters"
        Parameters:
          - S3BucketName
          - KeyPairName
          - ScratchVolumeSize
          - SpotBidPercentage
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - HighPriorityCEMinvCpus
          - HighPriorityCEMaxvCpus
          - DefaultRetryNumber
      - Label:
          default: "Job Definition"
        Parameters:
          - JobDefinitionName
          - Memory
          - Vcpus
          - Image
          - Command

      - Label:
          default: "Batch Launcher Server Parameters"
        Parameters:
          - ServerInstanceType
          - ServerInstanceName
          - ServerSSHLocation

    ParameterLabels:
      TemplatePath:
        default: S3 key object (direcotry) name where templates locate.
      S3BucketName:
        default: S3 Bucket Name
      KeyPairName:
        default: EC2 Key Pair Name
      ScratchVolumeSize:
        default: Custom AMI initial scratch volume
      SpotBidPercentage:
        default: Spot Bid %
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU
      HighPriorityCEMinvCpus:
        default: High Priority Min vCPU
      HighPriorityCEMaxvCpus:
        default: High Priority Max vCPU
      DefaultRetryNumber:
        default: Job Retry Attempts
      ServerInstanceType:
        default: Bastion Server Instance Type
      ServerInstanceName:
        default: Bastion Server Instance Name
      ServerSSHLocation:
        default: Bastion Server SSH Location


Parameters:
  TemplatePath:
    Type: String
    Description: S3Bucket Path where the templates are stored
    Default: s4-valinor-cloudformation-templates
  S3BucketName:
    Description: A S3 bucket name for storing analysis results
    Type: String
  AvailabilityZone1:
    Description: The first availability zone in the region
    Type: AWS::EC2::AvailabilityZone::Name
    ConstraintDescription: Must be a valid availability zone
    Default: us-east-1a
  AvailabilityZone2:
    Description: The second availability zone in the region
    Type: AWS::EC2::AvailabilityZone::Name
    ConstraintDescription: Must be a valid availability zone
    Default: us-east-1b
  GlobalCIDR:
    Description: Global CIDR of the VPC  ( i.e. 10.80.191.0/24 - Total 256 IPs )
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.0/24
  PubNet1:
    Description: 1st Public Subnet Network (i.e. 10.80.191.0/26 - Total 64 IPs )
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.0/26
  PubNet2:
    Description: 2nd Public Subnet Network (i.e. 10.80.191.64/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.64/26
  PrivNet1:
    Description: 1nd Private Subnet Network (i.e. 10.80.191.128/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.128/26
  PrivNet2:
    Description: 2nd Private Subnet Network (i.e. 10.80.191.192/26 - Total 64 IPs)
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.80.191.192/26
  KeyPairName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
  ScratchVolumeSize:
    Description: AMI initial scratch volume
    Type: Number
  SpotBidPercentage:
    Description: The percent of on-demand pricing for max bid for Spot intances
    Type: Number
    Default: 100
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 1024
  HighPriorityCEMinvCpus:
    Description: The minimum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 0
  HighPriorityCEMaxvCpus:
    Description: The maximum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 1024
  DefaultRetryNumber:
    Description: The default number of Job retry attempts
    Type: Number
    Default: 3

  JobDefinitionName:
    Description: Name of Job Definition
    Type: String
    Default: Image2Thumbnail
  Memory :
    Type: Number
    Description: The hard limit (in MiB) of memory to present to the job container
    Default: 2000
  Vcpus :
    Type: Number
    Description: The number of vCPUs reserved for the job container.
    Default: 2
  Image :
    Description: The image used to start a container.
    Type: String
    Default: 260062248592.dkr.ecr.us-east-1.amazonaws.com/s4-aws-batch-demo
  Command:
    Description: The command that is passed to the container.
    Type: String
    Default: python image_to_thumbnail.py

  ServerInstanceType:
    Description: >-
      EC2 instance type.  Bastion itself does not require much compute power.
      A t2.medium should be sufficient.  If you want to run this server on the
      free tier, use a t2.micro.
    Type: String
    Default: t2.medium
    AllowedValues:
    - t2.micro
    - t2.medium
    - t2.large
    ConstraintDescription: "Must be 't2.micro', 't2.medium', or 't2.large'."
  ServerInstanceName:
    Type: String
    Default: bastion-server
    Description: The name of the instance that is created
  ServerSSHLocation:
    Description: " The IP address range that can be used to SSH to the EC2 instances"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  HTTPLocation:
    Description: "The IP address range that has HTTP access to the EC2 instances"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/sema4-vpc.yaml"
      TimeoutInMinutes: '20'
      Parameters:
        GlobalCIDR: !Ref GlobalCIDR
        PubNet1:  !Ref PubNet1
        PubNet2: !Ref PubNet2
        PrivNet1: !Ref PrivNet1
        PrivNet2: !Ref PrivNet2
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
  AMIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-custom-ami.template.yaml"
      TimeoutInMinutes: '20'
      Parameters:
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        PublicSubnetID: !Sub ${VPCStack.Outputs.PublicSubnet2}
        ScratchMountPoint: /scratch
        ScratchVolumeSize: !Ref ScratchVolumeSize
        UseEncryption: Yes
        KeyName: !Ref KeyPairName
        AMIType: default
        AMIName: !Join ["-", ["bastion-ami", !Select [2, !Split ["/", !Ref "AWS::StackId" ]]]]
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-s3.template.yaml"
      TimeoutInMinutes: '10'
      Parameters:
        S3BucketName: !Ref S3BucketName
  IamStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-iam.template.yaml"
      TimeoutInMinutes: '20'
      Parameters:
        S3BucketName: !Ref S3BucketName
  BatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamStack
      - VPCStack
      - AMIStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/aws-genomics-batch.template.yaml"
      TimeoutInMinutes: "30"
      Parameters:
        CustomAmiId: !Sub ${AMIStack.Outputs.AMI}
        Ec2KeyPairName: !Ref KeyPairName
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        SubnetIds: !Sub "${VPCStack.Outputs.PrivateSubnet1},${VPCStack.Outputs.PrivateSubnet2}"
        SpotBidPercentage: !Ref SpotBidPercentage
        DefaultCEMinvCpus: !Ref DefaultCEMinvCpus
        DefaultCEMaxvCpus: !Ref DefaultCEMaxvCpus
        HighPriorityCEMinvCpus: !Ref HighPriorityCEMinvCpus
        HighPriorityCEMaxvCpus: !Ref HighPriorityCEMaxvCpus
        DefaultRetryNumber: !Ref DefaultRetryNumber
        BatchServiceRoleArn: !Sub ${IamStack.Outputs.BatchServiceRoleArn}
        Ec2InstanceProfileArn: !Sub ${IamStack.Outputs.BatchInstanceProfileArn}
        SpotFleetRoleArn: !Sub ${IamStack.Outputs.BatchSpotFleetRoleArn}

  BatchJobDefStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BatchStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/sema4-example-jobdef.template.yaml"
      TimeoutInMinutes: "30"
      Parameters:
        JobDefinitionName: !Ref JobDefinitionName
        JobRoleArn: !Sub ${IamStack.Outputs.BatchJobRoleArn}
        Vcpus: !Ref Vcpus
        Memory: !Ref Memory
        Image: !Ref Image

  EC2InstanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BatchJobDefStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/sema4-ec2.template.yaml"
      TimeoutInMinutes: "30"
      Parameters:
        InstanceType: !Ref ServerInstanceType
        VpcId: !Sub ${VPCStack.Outputs.VPCId}
        PublicSubnetID: !Sub ${VPCStack.Outputs.PublicSubnet2}
        InstanceName: !Ref ServerInstanceName
        KeyName: !Ref KeyPairName
        SSHLocation: !Ref ServerSSHLocation
        S3BucketName: !Ref S3BucketName
        BatchQueue: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
        JobDefinition: !Ref JobDefinitionName

Outputs:
  GenomicsEnvS3Bucket:
    Value: !Sub ${S3Stack.Outputs.BucketName}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-S3Bucket"
  GenomicsEnvBatchJobRoleArn:
    Value: !Sub ${IamStack.Outputs.BatchJobRoleArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-BatchJobRoleArn"
  GenomicsEnvDefaultJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-DefaultJobQueueArn"
  GenomicsEnvHighPriorityJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.HighPriorityJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-HighPriorityJobQueueArn"

  ServerEC2Instance:
    Description: The EC2 Instance ID of your Bastion Server
    Value: !Sub ${EC2InstanceStack.Outputs.EC2Instance}

  ServerPublicIp:
    Value: !Sub ${EC2InstanceStack.Outputs.PublicIp}
    Description: Bastion server public IP address

  ServerHostName:
    Value: !Sub ${EC2InstanceStack.Outputs.HostName}
    Description: Bastion server public DNS name

