AWSTemplateFormatVersion: 2010-09-09
Description: >
    Deploys resource for a Job Definition.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Batch Job Definition"
        Parameters:
        - JobDefinitionName
        - Memory
        - Vcpus
        - Image
        - JobRoleArn

Parameters:
  JobDefinitionName:
    Description: Name of Job Definition
    Type: String
  Memory :
    Type: Number
    Description: The hard limit (in MiB) of memory to present to the job container
    Default: 2000
  Vcpus :
    Type: Number
    Description: The number of vCPUs reserved for the job container.
    Default: 2
  Image :
    Description: The image used to start a container.
    Type: String
  JobRoleArn:
    Description: The Amazon Resource Name (ARN) of the IAM role that the container can assume for AWS permissions.
    Type: String

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Ref JobDefinitionName
      ContainerProperties:
        Privileged: true
        JobRoleArn: !Ref JobRoleArn
        Vcpus: !Ref Vcpus
        Memory: !Ref Memory
        Image: !Ref Image
Outputs:
  JobDefinitionName:
    Value: !Ref JobDefinitionName
  JobDefinitionArn:
    Value: !Ref JobDefinition